package engine.damage;

import java.awt.Color;
import java.awt.Graphics;

import engine.StatusEffect;
import utility.Vector2D;

/**
 * 
 * Mage's E-ability, applies a defence debuff to near by enemies
 * @author Callum
 *
 */
public class MageDebuff extends CircleDamageSource {

	/**
	 * Initialises a mage debuff attack
	 * @param pos the position of the attack
	 * @param rad the radius of the effect
	 * @param d the length of the effect
	 * @param p whether the effect was generated by a player
	 * @param id the id of the LivingEntity that created this
	 */
	public MageDebuff(Vector2D pos, int rad, int d, boolean p, long id) {
		super(pos, rad, 0, d, false, p, 0, new StatusEffect(1, 0, 0.75, StatusEffect.DEF, true), 0, id);
	}

	@Override
	public void draw(Graphics g, Vector2D offset) {
		g.setColor(new Color(0, 0, 0, 64));
		Vector2D pos = getHitbox().getPosition().add(offset);
		int radius = getHitbox().getRadius();
		g.fillOval((int) pos.getX() - radius, (int) pos.getY() - radius, radius * 2, radius * 2);
	}
}
